// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: TonexOneController_085pj

#ifndef _TONEXONECONTROLLER_085PJ_UI_H
#define _TONEXONECONTROLLER_085PJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_PresetHeadingLabel;
extern lv_obj_t * ui_BottomContainer;
extern lv_obj_t * ui_PresetHeadingLabel2;
extern lv_obj_t * ui_TopPanel;
extern lv_obj_t * ui_USBStatusOK;
extern lv_obj_t * ui_USBStatusFail;
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_BTStatusDisconn;
extern lv_obj_t * ui_BTStatusConn;
extern lv_obj_t * ui_WiFiStatusDisconn;
extern lv_obj_t * ui_WiFiStatusConn;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_usb_ok_png);    // assets/usb_ok.png
LV_IMG_DECLARE(ui_img_usb_fail_png);    // assets/usb_fail.png
LV_IMG_DECLARE(ui_img_smythbuilt_png);    // assets/smythbuilt.png
LV_IMG_DECLARE(ui_img_bt_disconn_png);    // assets/bt_disconn.png
LV_IMG_DECLARE(ui_img_bt_conn_png);    // assets/bt_conn.png
LV_IMG_DECLARE(ui_img_wifi_disconn_png);    // assets/wifi_disconn.png
LV_IMG_DECLARE(ui_img_wifi_conn_png);    // assets/wifi_conn.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
