// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_BottomPanel;
void ui_event_PreviousContainer(lv_event_t * e);
lv_obj_t * ui_PreviousContainer;
void ui_event_PreviousButton(lv_event_t * e);
lv_obj_t * ui_PreviousButton;
void ui_event_Footswitch1Label(lv_event_t * e);
lv_obj_t * ui_Footswitch1Label;
void ui_event_NextContainer(lv_event_t * e);
lv_obj_t * ui_NextContainer;
void ui_event_NextButton(lv_event_t * e);
lv_obj_t * ui_NextButton;
void ui_event_Footswitch2Label(lv_event_t * e);
lv_obj_t * ui_Footswitch2Label;
lv_obj_t * ui_TopPanel;
lv_obj_t * ui_IKLogo;
lv_obj_t * ui_BTStatusConn;
lv_obj_t * ui_BTStatusDisconn;
lv_obj_t * ui_USBStatusOK;
lv_obj_t * ui_USBStatusFail;
lv_obj_t * ui_ProjectHeadingLabel;
lv_obj_t * ui_AmpSkins;
lv_obj_t * ui_Ampjcm800;
lv_obj_t * ui_Amptwinreverb;
lv_obj_t * ui_Amp2001rb;
lv_obj_t * ui_Amp5150;
lv_obj_t * ui_AmpAcoustic360;
lv_obj_t * ui_Ampb18n;
lv_obj_t * ui_Ampb15n;
lv_obj_t * ui_AmpbBluesdeluxe;
lv_obj_t * ui_AmpbCustomDeluxe;
lv_obj_t * ui_AmpbDeville;
lv_obj_t * ui_AmpbDualrectifier;
lv_obj_t * ui_AmpbGoldfinger;
lv_obj_t * ui_AmpbInvader;
lv_obj_t * ui_AmpJazzchorus;
lv_obj_t * ui_AmpOr50;
lv_obj_t * ui_AmpPowerball;
lv_obj_t * ui_AmpPrinceton;
lv_obj_t * ui_AmpRockerverb;
lv_obj_t * ui_AmpSvtcl;
lv_obj_t * ui_AmpMaverick;
lv_obj_t * ui_AmpMk3;
lv_obj_t * ui_AmpSuperbass;
lv_obj_t * ui_AmpTrinity;
lv_obj_t * ui_AmpDumble;
lv_obj_t * ui_AmpJetcity;
lv_obj_t * ui_AmpAC30;
lv_obj_t * ui_AmpEvh5150;
lv_obj_t * ui_AmpTinyterror;
lv_obj_t * ui_Amp2020;
lv_obj_t * ui_AmpPinktaco;
lv_obj_t * ui_AmpSupro50;
lv_obj_t * ui_AmpDiezel;
void ui_event_PresetHeadingLabel(lv_event_t * e);
lv_obj_t * ui_PresetHeadingLabel;
void ui_event_PresetDetailsTextArea(lv_event_t * e);
lv_obj_t * ui_PresetDetailsTextArea;
void ui_event_LeftArrow(lv_event_t * e);
lv_obj_t * ui_LeftArrow;
void ui_event_RightArrow(lv_event_t * e);
lv_obj_t * ui_RightArrow;
void ui_event_EntryKeyboard(lv_event_t * e);
lv_obj_t * ui_EntryKeyboard;
void ui_event_OKTick(lv_event_t * e);
lv_obj_t * ui_OKTick;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_skin_[2] = {&ui_img_skin_2020_png, &ui_img_skin_5150_png};
const lv_img_dsc_t * ui_imgset_skin_ac[1] = {&ui_img_skin_ac30_png};
const lv_img_dsc_t * ui_imgset_skin_acoustic[1] = {&ui_img_skin_acoustic360_png};
const lv_img_dsc_t * ui_imgset_skin_evh[1] = {&ui_img_skin_evh5150_png};
const lv_img_dsc_t * ui_imgset_skin_jcm[1] = {&ui_img_skin_jcm800_png};
const lv_img_dsc_t * ui_imgset_skin_mk[1] = {&ui_img_skin_mk3_png};
const lv_img_dsc_t * ui_imgset_skin_or[1] = {&ui_img_skin_or50_png};
const lv_img_dsc_t * ui_imgset_skin_supro[1] = {&ui_img_skin_supro50_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_PreviousContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PreviousClicked(e);
    }
}
void ui_event_PreviousButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PreviousClicked(e);
    }
}
void ui_event_Footswitch1Label(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        PreviousClicked(e);
    }
}
void ui_event_NextContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        NextClicked(e);
    }
}
void ui_event_NextButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        NextClicked(e);
    }
}
void ui_event_Footswitch2Label(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        NextClicked(e);
    }
}
void ui_event_PresetHeadingLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_RightArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_PresetDetailsTextArea, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_OKTick, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_PresetDetailsTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_EntryKeyboard,  ui_PresetDetailsTextArea);
        _ui_flag_modify(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_LeftArrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        AmpSkinPrevious(e);
    }
}
void ui_event_RightArrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        AmpSkinNext(e);
    }
}
void ui_event_EntryKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        PresetDescriptionChanged(e);
    }
}
void ui_event_OKTick(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        SaveUserDataRequest(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_OKTick, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_RightArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_PresetDetailsTextArea, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
