// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_BottomPanel;
void ui_event_PreviousContainer(lv_event_t * e);
lv_obj_t * ui_PreviousContainer;
void ui_event_PreviousButton(lv_event_t * e);
lv_obj_t * ui_PreviousButton;
void ui_event_Footswitch1Label(lv_event_t * e);
lv_obj_t * ui_Footswitch1Label;
void ui_event_NextContainer(lv_event_t * e);
lv_obj_t * ui_NextContainer;
void ui_event_NextButton(lv_event_t * e);
lv_obj_t * ui_NextButton;
void ui_event_Footswitch2Label(lv_event_t * e);
lv_obj_t * ui_Footswitch2Label;
void ui_event_SettingsImage(lv_event_t * e);
lv_obj_t * ui_SettingsImage;
lv_obj_t * ui_TopPanel;
lv_obj_t * ui_IKLogo;
lv_obj_t * ui_BTStatusConn;
void ui_event_BTStatusDisconn(lv_event_t * e);
lv_obj_t * ui_BTStatusDisconn;
lv_obj_t * ui_USBStatusOK;
lv_obj_t * ui_USBStatusFail;
lv_obj_t * ui_ProjectHeadingLabel;
lv_obj_t * ui_Skins;
lv_obj_t * ui_SkinImage;
void ui_event_PresetHeadingLabel(lv_event_t * e);
lv_obj_t * ui_PresetHeadingLabel;
void ui_event_PresetDetailsTextArea(lv_event_t * e);
lv_obj_t * ui_PresetDetailsTextArea;
void ui_event_LeftArrow(lv_event_t * e);
lv_obj_t * ui_LeftArrow;
void ui_event_RightArrow(lv_event_t * e);
lv_obj_t * ui_RightArrow;
void ui_event_EntryKeyboard(lv_event_t * e);
lv_obj_t * ui_EntryKeyboard;
void ui_event_OKTick(lv_event_t * e);
lv_obj_t * ui_OKTick;
// CUSTOM VARIABLES


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
lv_obj_t * ui_Settings;
lv_obj_t * ui_SettingsTabview;
lv_obj_t * ui_NoiseGateTab;
lv_obj_t * ui_NoiseGateEnableGroup;
lv_obj_t * ui_NoiseGateSwitch;
lv_obj_t * ui_NoiseGateEnableLabel;
lv_obj_t * ui_NoiseGateThresholdGroup;
lv_obj_t * ui_NoiseGateThresholdSlider;
lv_obj_t * ui_NoiseGateThresholdLabel;
lv_obj_t * ui_NoiseGateReleaseGroup;
lv_obj_t * ui_NoiseGateReleaseSlider;
lv_obj_t * ui_NoiseGateReleaseLabel;
lv_obj_t * ui_NoiseGateDepthGroup;
lv_obj_t * ui_NoiseGateDepthSlider;
lv_obj_t * ui_NoiseGateDepthLabel;
lv_obj_t * ui_CompressorTag;
lv_obj_t * ui_CompressorEnableGroup;
lv_obj_t * ui_NoiseGateSwitch2;
lv_obj_t * ui_NoiseGateEnableLabel2;
lv_obj_t * ui_CompressorPostGroup;
lv_obj_t * ui_NoiseGateSwitch5;
lv_obj_t * ui_NoiseGateEnableLabel5;
lv_obj_t * ui_CompressorThresholdGroup;
lv_obj_t * ui_NoiseGateThresholdSlider2;
lv_obj_t * ui_NoiseGateThresholdLabel2;
lv_obj_t * ui_CompressorAttackGroup;
lv_obj_t * ui_NoiseGateThresholdSlider1;
lv_obj_t * ui_NoiseGateThresholdLabel1;
lv_obj_t * ui_CompressorMakeupGroup;
lv_obj_t * ui_NoiseGateThresholdSlider6;
lv_obj_t * ui_NoiseGateThresholdLabel6;
lv_obj_t * ui_EQTab;
lv_obj_t * ui_EQPrePostGroup;
lv_obj_t * ui_NoiseGateSwitch4;
lv_obj_t * ui_NoiseGateEnableLabel4;
lv_obj_t * ui_EQBassFreqGroup;
lv_obj_t * ui_NoiseGateThresholdSlider4;
lv_obj_t * ui_NoiseGateThresholdLabel4;
lv_obj_t * ui_EQMidFreqGroup;
lv_obj_t * ui_NoiseGateThresholdSlider3;
lv_obj_t * ui_NoiseGateThresholdLabel3;
lv_obj_t * ui_EQTrebleFreqGroup;
lv_obj_t * ui_NoiseGateThresholdSlider7;
lv_obj_t * ui_NoiseGateThresholdLabel7;
lv_obj_t * ui_ReverbPage;
lv_obj_t * ui_ReverbEnableGroup;
lv_obj_t * ui_NoiseGateSwitch3;
lv_obj_t * ui_NoiseGateEnableLabel3;
lv_obj_t * ui_ReverbMixGroup;
lv_obj_t * ui_NoiseGateThresholdSlider9;
lv_obj_t * ui_NoiseGateThresholdLabel9;
lv_obj_t * ui_ReverbMixGroup1;
lv_obj_t * ui_NoiseGateThresholdSlider8;
lv_obj_t * ui_NoiseGateThresholdLabel8;
lv_obj_t * ui_ReverbPredelayGroup;
lv_obj_t * ui_NoiseGateThresholdSlider11;
lv_obj_t * ui_NoiseGateThresholdLabel11;
lv_obj_t * ui_ReverbColorGroup;
lv_obj_t * ui_NoiseGateThresholdSlider12;
lv_obj_t * ui_NoiseGateThresholdLabel12;
lv_obj_t * ui_GlobalTab;
lv_obj_t * ui_GlobalInputTrimGroup;
lv_obj_t * ui_NoiseGateThresholdSlider5;
lv_obj_t * ui_NoiseGateThresholdLabel5;
lv_obj_t * ui_GlobalVolumeGroup;
lv_obj_t * ui_NoiseGateThresholdSlider10;
lv_obj_t * ui_NoiseGateThresholdLabel10;
lv_obj_t * ui_GlobalCabinetGroup;
lv_obj_t * ui_NoiseGateSwitch6;
lv_obj_t * ui_NoiseGateEnableLabel6;
void ui_event_CloseImage(lv_event_t * e);
lv_obj_t * ui_CloseImage;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_pskin_mxr[1] = {&ui_img_pskin_mxr2_png};
const lv_img_dsc_t * ui_imgset_pskin_od[1] = {&ui_img_pskin_od1_png};
const lv_img_dsc_t * ui_imgset_skin_[2] = {&ui_img_skin_2020_png, &ui_img_skin_5150_png};
const lv_img_dsc_t * ui_imgset_skin_ac[1] = {&ui_img_skin_ac30_png};
const lv_img_dsc_t * ui_imgset_skin_evh[1] = {&ui_img_skin_evh5150_png};
const lv_img_dsc_t * ui_imgset_skin_jcm[1] = {&ui_img_skin_jcm800_png};
const lv_img_dsc_t * ui_imgset_skin_mk[1] = {&ui_img_skin_mk3_png};
const lv_img_dsc_t * ui_imgset_skin_or[1] = {&ui_img_skin_or50_png};
const lv_img_dsc_t * ui_imgset_skin_supro[1] = {&ui_img_skin_supro50_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_PreviousContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PreviousClicked(e);
    }
}

void ui_event_PreviousButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PreviousClicked(e);
    }
}

void ui_event_Footswitch1Label(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PreviousClicked(e);
    }
}

void ui_event_NextContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NextClicked(e);
    }
}

void ui_event_NextButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NextClicked(e);
    }
}

void ui_event_Footswitch2Label(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NextClicked(e);
    }
}

void ui_event_SettingsImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_BTStatusDisconn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        BTBondsClearRequest(e);
    }
}

void ui_event_PresetHeadingLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_RightArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_PresetDetailsTextArea, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_OKTick, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_PresetDetailsTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_EntryKeyboard,  ui_PresetDetailsTextArea);
        _ui_flag_modify(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_LeftArrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AmpSkinPrevious(e);
    }
}

void ui_event_RightArrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AmpSkinNext(e);
    }
}

void ui_event_EntryKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        PresetDescriptionChanged(e);
    }
}

void ui_event_OKTick(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SaveUserDataRequest(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_OKTick, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_RightArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_PresetDetailsTextArea, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_CloseImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Settings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
