// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#ifndef _TONEX_CONTROLLER_UI_H
#define _TONEX_CONTROLLER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_BottomPanel;
void ui_event_PreviousContainer(lv_event_t * e);
extern lv_obj_t * ui_PreviousContainer;
void ui_event_PreviousButton(lv_event_t * e);
extern lv_obj_t * ui_PreviousButton;
void ui_event_Footswitch1Label(lv_event_t * e);
extern lv_obj_t * ui_Footswitch1Label;
void ui_event_NextContainer(lv_event_t * e);
extern lv_obj_t * ui_NextContainer;
void ui_event_NextButton(lv_event_t * e);
extern lv_obj_t * ui_NextButton;
void ui_event_Footswitch2Label(lv_event_t * e);
extern lv_obj_t * ui_Footswitch2Label;
extern lv_obj_t * ui_TopPanel;
extern lv_obj_t * ui_IKLogo;
extern lv_obj_t * ui_BTStatusConn;
void ui_event_BTStatusDisconn(lv_event_t * e);
extern lv_obj_t * ui_BTStatusDisconn;
extern lv_obj_t * ui_USBStatusOK;
extern lv_obj_t * ui_USBStatusFail;
extern lv_obj_t * ui_ProjectHeadingLabel;
extern lv_obj_t * ui_Skins;
extern lv_obj_t * ui_SkinImage;
void ui_event_PresetHeadingLabel(lv_event_t * e);
extern lv_obj_t * ui_PresetHeadingLabel;
void ui_event_PresetDetailsTextArea(lv_event_t * e);
extern lv_obj_t * ui_PresetDetailsTextArea;
void ui_event_LeftArrow(lv_event_t * e);
extern lv_obj_t * ui_LeftArrow;
void ui_event_RightArrow(lv_event_t * e);
extern lv_obj_t * ui_RightArrow;
void ui_event_EntryKeyboard(lv_event_t * e);
extern lv_obj_t * ui_EntryKeyboard;
void ui_event_OKTick(lv_event_t * e);
extern lv_obj_t * ui_OKTick;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_previous_png);    // assets/previous.png
LV_IMG_DECLARE(ui_img_previous_down_png);    // assets/previous_down.png
LV_IMG_DECLARE(ui_img_next_png);    // assets/next.png
LV_IMG_DECLARE(ui_img_next_down_png);    // assets/next_down.png
LV_IMG_DECLARE(ui_img_smythbuilt_png);    // assets/smythbuilt.png
LV_IMG_DECLARE(ui_img_bt_conn_png);    // assets/bt_conn.png
LV_IMG_DECLARE(ui_img_bt_disconn_png);    // assets/bt_disconn.png
LV_IMG_DECLARE(ui_img_usb_ok_png);    // assets/usb_ok.png
LV_IMG_DECLARE(ui_img_usb_fail_png);    // assets/usb_fail.png
LV_IMG_DECLARE(ui_img_skin_jcm800_png);    // assets/skin_jcm800.png
LV_IMG_DECLARE(ui_img_arrow_left_png);    // assets/arrow_left.png
LV_IMG_DECLARE(ui_img_arrow_right_png);    // assets/arrow_right.png
LV_IMG_DECLARE(ui_img_tick_png);    // assets/tick.png
LV_IMG_DECLARE(ui_img_pskin_arion_png);    // assets/pskin_arion.png
LV_IMG_DECLARE(ui_img_pskin_bigmuff_png);    // assets/pskin_bigmuff.png
LV_IMG_DECLARE(ui_img_pskin_darkglass_png);    // assets/pskin_darkglass.png
LV_IMG_DECLARE(ui_img_pskin_dod_png);    // assets/pskin_dod.png
LV_IMG_DECLARE(ui_img_pskin_ehx_png);    // assets/pskin_ehx.png
LV_IMG_DECLARE(ui_img_pskin_fender_png);    // assets/pskin_fender.png
LV_IMG_DECLARE(ui_img_pskin_fulltone_png);    // assets/pskin_fulltone.png
LV_IMG_DECLARE(ui_img_pskin_fzs_png);    // assets/pskin_fzs.png
LV_IMG_DECLARE(ui_img_pskin_jhs_png);    // assets/pskin_jhs.png
LV_IMG_DECLARE(ui_img_pskin_klon_png);    // assets/pskin_klon.png
LV_IMG_DECLARE(ui_img_pskin_landgraf_png);    // assets/pskin_landgraf.png
LV_IMG_DECLARE(ui_img_pskin_mxr_png);    // assets/pskin_mxr.png
LV_IMG_DECLARE(ui_img_pskin_mxr2_png);    // assets/pskin_mxr2.png
LV_IMG_DECLARE(ui_img_pskin_od1_png);    // assets/pskin_od1.png
LV_IMG_DECLARE(ui_img_pskin_plimsoul_png);    // assets/pskin_plimsoul.png
LV_IMG_DECLARE(ui_img_pskin_rogermayer_png);    // assets/pskin_rogermayer.png
LV_IMG_DECLARE(ui_img_pskin_seymour_png);    // assets/pskin_seymour.png
LV_IMG_DECLARE(ui_img_pskin_strymon_png);    // assets/pskin_strymon.png
LV_IMG_DECLARE(ui_img_pskin_trex_png);    // assets/pskin_trex.png
LV_IMG_DECLARE(ui_img_pskin_tubescreamer_png);    // assets/pskin_tubescreamer.png
LV_IMG_DECLARE(ui_img_pskin_wampler_png);    // assets/pskin_wampler.png
LV_IMG_DECLARE(ui_img_pskin_zvex_png);    // assets/pskin_zvex.png
LV_IMG_DECLARE(ui_img_skin_2001rb_png);    // assets/skin_2001rb.png
LV_IMG_DECLARE(ui_img_skin_2020_png);    // assets/skin_2020.png
LV_IMG_DECLARE(ui_img_skin_5150_png);    // assets/skin_5150.png
LV_IMG_DECLARE(ui_img_skin_ac30_png);    // assets/skin_ac30.png
LV_IMG_DECLARE(ui_img_skin_b18n_png);    // assets/skin_b18n.png
LV_IMG_DECLARE(ui_img_skin_bluesdeluxe_png);    // assets/skin_bluesdeluxe.png
LV_IMG_DECLARE(ui_img_skin_deville_png);    // assets/skin_deville.png
LV_IMG_DECLARE(ui_img_skin_diezel_png);    // assets/skin_diezel.png
LV_IMG_DECLARE(ui_img_skin_dualrectifier_png);    // assets/skin_dualrectifier.png
LV_IMG_DECLARE(ui_img_skin_dumble_png);    // assets/skin_dumble.png
LV_IMG_DECLARE(ui_img_skin_evh5150_png);    // assets/skin_evh5150.png
LV_IMG_DECLARE(ui_img_skin_goldfinger_png);    // assets/skin_goldfinger.png
LV_IMG_DECLARE(ui_img_skin_invader_png);    // assets/skin_invader.png
LV_IMG_DECLARE(ui_img_skin_jazzchorus_png);    // assets/skin_jazzchorus.png
LV_IMG_DECLARE(ui_img_skin_jetcity_png);    // assets/skin_jetcity.png
LV_IMG_DECLARE(ui_img_skin_maverick_png);    // assets/skin_maverick.png
LV_IMG_DECLARE(ui_img_skin_mk3_png);    // assets/skin_mk3.png
LV_IMG_DECLARE(ui_img_skin_or50_png);    // assets/skin_or50.png
LV_IMG_DECLARE(ui_img_skin_pinktaco_png);    // assets/skin_pinktaco.png
LV_IMG_DECLARE(ui_img_skin_powerball_png);    // assets/skin_powerball.png
LV_IMG_DECLARE(ui_img_skin_princeton_png);    // assets/skin_princeton.png
LV_IMG_DECLARE(ui_img_skin_superbass_png);    // assets/skin_superbass.png
LV_IMG_DECLARE(ui_img_skin_supro50_png);    // assets/skin_supro50.png
LV_IMG_DECLARE(ui_img_skin_svtcl_png);    // assets/skin_svtcl.png
LV_IMG_DECLARE(ui_img_skin_twinreverb_png);    // assets/skin_twinreverb.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
