// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PreviousClicked(lv_event_t * e);
void NextClicked(lv_event_t * e);
void toggle_effect_gate(lv_event_t * e);
void toggle_effect_amp(lv_event_t * e);
void toggle_effect_cab(lv_event_t * e);
void toggle_effect_comp(lv_event_t * e);
void toggle_effect_mod(lv_event_t * e);
void toggle_effect_delay(lv_event_t * e);
void toggle_effect_reverb(lv_event_t * e);
void BTBondsClearRequest(lv_event_t * e);
void AmpSkinPrevious(lv_event_t * e);
void AmpSkinNext(lv_event_t * e);
void PresetDescriptionChanged(lv_event_t * e);
void SaveUserDataRequest(lv_event_t * e);
void ParameterChanged(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
