// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#include "ui.h"

void PreviousClicked(lv_event_t * e)
{
	// Your code here
}

void NextClicked(lv_event_t * e)
{
	// Your code here
}

void BankAClicked(lv_event_t * e)
{
	// Your code here
}

void BankBClicked(lv_event_t * e)
{
	// Your code here
}

void AmpSkinPrevious(lv_event_t * e)
{
	// Your code here
}

void AmpSkinNext(lv_event_t * e)
{
	// Your code here
}

void PresetDescriptionChanged(lv_event_t * e)
{
	// Your code here
}

void SaveUserDataRequest(lv_event_t * e)
{
	// Your code here
}
