// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: TonexOneController_1.69pj

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C"
{
#endif

    void NextClicked(lv_event_t* e);
    void PreviousClicked(lv_event_t* e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
