// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: TonexOneController_1.69pj

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetHeadingLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PresetHeadingLabel, 220);
    lv_obj_set_height(ui_PresetHeadingLabel, 50);
    lv_obj_set_x(ui_PresetHeadingLabel, -1);
    lv_obj_set_y(ui_PresetHeadingLabel, -53);
    lv_obj_set_align(ui_PresetHeadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetHeadingLabel, "?\n");
    lv_obj_set_style_text_color(ui_PresetHeadingLabel, lv_color_hex(0xD1A60C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetHeadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetHeadingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetHeadingLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_BottomContainer);
    lv_obj_set_width(ui_BottomContainer, 228);
    lv_obj_set_height(ui_BottomContainer, 141);
    lv_obj_set_x(ui_BottomContainer, 0);
    lv_obj_set_y(ui_BottomContainer, 51);
    lv_obj_set_align(ui_BottomContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BottomContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BottomContainer, lv_color_hex(0x262525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BottomContainer, lv_color_hex(0x563F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BottomContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BottomContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_outline_color(ui_BottomContainer, lv_color_hex(0xFCA204), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BottomContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PresetHeadingLabel2 = lv_label_create(ui_BottomContainer);
    lv_obj_set_width(ui_PresetHeadingLabel2, 212);
    lv_obj_set_height(ui_PresetHeadingLabel2, 122);
    lv_obj_set_x(ui_PresetHeadingLabel2, -1);
    lv_obj_set_y(ui_PresetHeadingLabel2, 0);
    lv_obj_set_align(ui_PresetHeadingLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresetHeadingLabel2, "Preset Name\n");
    lv_obj_set_style_text_align(ui_PresetHeadingLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetHeadingLabel2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopPanel = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_TopPanel);
    lv_obj_set_width(ui_TopPanel, 240);
    lv_obj_set_height(ui_TopPanel, 48);
    lv_obj_set_x(ui_TopPanel, 0);
    lv_obj_set_y(ui_TopPanel, -117);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_USBStatusOK = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_USBStatusOK, &ui_img_usb_ok_png);
    lv_obj_set_width(ui_USBStatusOK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_USBStatusOK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_USBStatusOK, 87);
    lv_obj_set_y(ui_USBStatusOK, 0);
    lv_obj_set_align(ui_USBStatusOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_USBStatusOK, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_USBStatusOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_USBStatusOK, 220);

    ui_USBStatusFail = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_USBStatusFail, &ui_img_usb_fail_png);
    lv_obj_set_width(ui_USBStatusFail, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_USBStatusFail, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_USBStatusFail, 87);
    lv_obj_set_y(ui_USBStatusFail, 0);
    lv_obj_set_align(ui_USBStatusFail, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_USBStatusFail, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_USBStatusFail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_USBStatusFail, 220);

    ui_Logo = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_Logo, &ui_img_smythbuilt_png);
    lv_obj_set_width(ui_Logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Logo, -67);
    lv_obj_set_y(ui_Logo, 4);
    lv_obj_set_align(ui_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Logo, 200);

    ui_BTStatusDisconn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_BTStatusDisconn, &ui_img_bt_disconn_png);
    lv_obj_set_width(ui_BTStatusDisconn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatusDisconn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatusDisconn, 44);
    lv_obj_set_y(ui_BTStatusDisconn, -1);
    lv_obj_set_align(ui_BTStatusDisconn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTStatusDisconn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTStatusDisconn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTStatusDisconn, 220);

    ui_BTStatusConn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_BTStatusConn, &ui_img_bt_conn_png);
    lv_obj_set_width(ui_BTStatusConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatusConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatusConn, 44);
    lv_obj_set_y(ui_BTStatusConn, -1);
    lv_obj_set_align(ui_BTStatusConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTStatusConn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTStatusConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTStatusConn, 220);

    ui_WiFiStatusDisconn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_WiFiStatusDisconn, &ui_img_wifi_disconn_png);
    lv_obj_set_width(ui_WiFiStatusDisconn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatusDisconn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatusDisconn, 9);
    lv_obj_set_y(ui_WiFiStatusDisconn, -1);
    lv_obj_set_align(ui_WiFiStatusDisconn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiStatusDisconn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiStatusDisconn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WiFiStatusDisconn, 220);

    ui_WiFiStatusConn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_WiFiStatusConn, &ui_img_wifi_conn_png);
    lv_obj_set_width(ui_WiFiStatusConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatusConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatusConn, 9);
    lv_obj_set_y(ui_WiFiStatusConn, -1);
    lv_obj_set_align(ui_WiFiStatusConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiStatusConn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiStatusConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WiFiStatusConn, 220);


}
