// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BottomPanel, 800);
    lv_obj_set_height(ui_BottomPanel, 71);
    lv_obj_set_x(ui_BottomPanel, 0);
    lv_obj_set_y(ui_BottomPanel, 203);
    lv_obj_set_align(ui_BottomPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BottomPanel, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BottomPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BottomPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PreviousContainer = lv_obj_create(ui_BottomPanel);
    lv_obj_remove_style_all(ui_PreviousContainer);
    lv_obj_set_width(ui_PreviousContainer, 221);
    lv_obj_set_height(ui_PreviousContainer, 58);
    lv_obj_set_x(ui_PreviousContainer, -200);
    lv_obj_set_y(ui_PreviousContainer, 0);
    lv_obj_set_align(ui_PreviousContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PreviousContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PreviousButton = lv_imgbtn_create(ui_PreviousContainer);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_previous_png, NULL);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_previous_down_png, NULL);
    lv_obj_set_height(ui_PreviousButton, 45);
    lv_obj_set_width(ui_PreviousButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_PreviousButton, 69);
    lv_obj_set_y(ui_PreviousButton, 0);
    lv_obj_set_align(ui_PreviousButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PreviousButton, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Footswitch1Label = lv_label_create(ui_PreviousContainer);
    lv_obj_set_width(ui_Footswitch1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Footswitch1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Footswitch1Label, -32);
    lv_obj_set_y(ui_Footswitch1Label, -4);
    lv_obj_set_align(ui_Footswitch1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Footswitch1Label, "Previous");
    lv_obj_set_style_text_color(ui_Footswitch1Label, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Footswitch1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Footswitch1Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextContainer = lv_obj_create(ui_BottomPanel);
    lv_obj_remove_style_all(ui_NextContainer);
    lv_obj_set_width(ui_NextContainer, 221);
    lv_obj_set_height(ui_NextContainer, 58);
    lv_obj_set_x(ui_NextContainer, 200);
    lv_obj_set_y(ui_NextContainer, 0);
    lv_obj_set_align(ui_NextContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NextContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextButton = lv_imgbtn_create(ui_NextContainer);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_next_png, NULL);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_next_down_png, NULL);
    lv_obj_set_height(ui_NextButton, 45);
    lv_obj_set_width(ui_NextButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_NextButton, 44);
    lv_obj_set_y(ui_NextButton, 0);
    lv_obj_set_align(ui_NextButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NextButton, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Footswitch2Label = lv_label_create(ui_NextContainer);
    lv_obj_set_width(ui_Footswitch2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Footswitch2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Footswitch2Label, -30);
    lv_obj_set_y(ui_Footswitch2Label, -2);
    lv_obj_set_align(ui_Footswitch2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Footswitch2Label, "Next");
    lv_obj_set_style_text_color(ui_Footswitch2Label, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Footswitch2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Footswitch2Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsImage = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_SettingsImage, &ui_img_settings_png);
    lv_obj_set_width(ui_SettingsImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsImage, 366);
    lv_obj_set_y(ui_SettingsImage, 1);
    lv_obj_set_align(ui_SettingsImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsImage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TopPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopPanel, 800);
    lv_obj_set_height(ui_TopPanel, 51);
    lv_obj_set_x(ui_TopPanel, 1);
    lv_obj_set_y(ui_TopPanel, -215);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IKLogo = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_IKLogo, &ui_img_smythbuilt_png);
    lv_obj_set_width(ui_IKLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IKLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IKLogo, -331);
    lv_obj_set_y(ui_IKLogo, 0);
    lv_obj_set_align(ui_IKLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IKLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IKLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTStatusConn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_BTStatusConn, &ui_img_bt_conn_png);
    lv_obj_set_width(ui_BTStatusConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatusConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatusConn, 301);
    lv_obj_set_y(ui_BTStatusConn, -2);
    lv_obj_set_align(ui_BTStatusConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTStatusConn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTStatusConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTStatusDisconn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_BTStatusDisconn, &ui_img_bt_disconn_png);
    lv_obj_set_width(ui_BTStatusDisconn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatusDisconn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatusDisconn, 301);
    lv_obj_set_y(ui_BTStatusDisconn, -2);
    lv_obj_set_align(ui_BTStatusDisconn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTStatusDisconn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTStatusDisconn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_USBStatusOK = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_USBStatusOK, &ui_img_usb_ok_png);
    lv_obj_set_width(ui_USBStatusOK, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_USBStatusOK, LV_SIZE_CONTENT);    /// 77
    lv_obj_set_x(ui_USBStatusOK, 356);
    lv_obj_set_y(ui_USBStatusOK, -1);
    lv_obj_set_align(ui_USBStatusOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_USBStatusOK, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_USBStatusOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_USBStatusFail = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_USBStatusFail, &ui_img_usb_fail_png);
    lv_obj_set_width(ui_USBStatusFail, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_USBStatusFail, LV_SIZE_CONTENT);    /// 77
    lv_obj_set_x(ui_USBStatusFail, 356);
    lv_obj_set_y(ui_USBStatusFail, -1);
    lv_obj_set_align(ui_USBStatusFail, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_USBStatusFail, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_USBStatusFail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiStatusConn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_WiFiStatusConn, &ui_img_wifi_conn_png);
    lv_obj_set_width(ui_WiFiStatusConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatusConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatusConn, 257);
    lv_obj_set_y(ui_WiFiStatusConn, 0);
    lv_obj_set_align(ui_WiFiStatusConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiStatusConn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiStatusConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiStatusDisconn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_WiFiStatusDisconn, &ui_img_wifi_disconn_png);
    lv_obj_set_width(ui_WiFiStatusDisconn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatusDisconn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatusDisconn, 257);
    lv_obj_set_y(ui_WiFiStatusDisconn, 0);
    lv_obj_set_align(ui_WiFiStatusDisconn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiStatusDisconn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiStatusDisconn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProjectHeadingLabel = lv_label_create(ui_TopPanel);
    lv_obj_set_width(ui_ProjectHeadingLabel, 508);
    lv_obj_set_height(ui_ProjectHeadingLabel, 38);
    lv_obj_set_align(ui_ProjectHeadingLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ProjectHeadingLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_ProjectHeadingLabel, "TONEX Controller");
    lv_obj_set_style_text_color(ui_ProjectHeadingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProjectHeadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProjectHeadingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProjectHeadingLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Skins = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Skins);
    lv_obj_set_width(ui_Skins, 460);
    lv_obj_set_height(ui_Skins, 143);
    lv_obj_set_x(ui_Skins, 0);
    lv_obj_set_y(ui_Skins, -20);
    lv_obj_set_align(ui_Skins, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Skins, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SkinImage = lv_img_create(ui_Skins);
    lv_img_set_src(ui_SkinImage, &ui_img_skin_jcm800_png);
    lv_obj_set_width(ui_SkinImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SkinImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SkinImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SkinImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SkinImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PresetHeadingLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PresetHeadingLabel, 789);
    lv_obj_set_height(ui_PresetHeadingLabel, 60);
    lv_obj_set_x(ui_PresetHeadingLabel, 0);
    lv_obj_set_y(ui_PresetHeadingLabel, -136);
    lv_obj_set_align(ui_PresetHeadingLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PresetHeadingLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_PresetHeadingLabel, "Preset Name");
    lv_obj_add_flag(ui_PresetHeadingLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_PresetHeadingLabel, lv_color_hex(0xD1A60C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetHeadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetHeadingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetHeadingLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetDetailsTextArea = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_PresetDetailsTextArea, 773);
    lv_obj_set_height(ui_PresetDetailsTextArea, 99);
    lv_obj_set_x(ui_PresetDetailsTextArea, 0);
    lv_obj_set_y(ui_PresetDetailsTextArea, 110);
    lv_obj_set_align(ui_PresetDetailsTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PresetDetailsTextArea, 128);
    lv_textarea_set_placeholder_text(ui_PresetDetailsTextArea, "Preset Description...");
    lv_obj_add_state(ui_PresetDetailsTextArea, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_font(ui_PresetDetailsTextArea, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetDetailsTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetDetailsTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetDetailsTextArea, lv_color_hex(0x563F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetDetailsTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_LeftArrow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_LeftArrow, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_LeftArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LeftArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LeftArrow, -270);
    lv_obj_set_y(ui_LeftArrow, -15);
    lv_obj_set_align(ui_LeftArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LeftArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RightArrow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_RightArrow, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_RightArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RightArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RightArrow, 270);
    lv_obj_set_y(ui_RightArrow, -15);
    lv_obj_set_align(ui_RightArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RightArrow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RightArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EntryKeyboard = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_EntryKeyboard, 799);
    lv_obj_set_height(ui_EntryKeyboard, 287);
    lv_obj_set_x(ui_EntryKeyboard, 0);
    lv_obj_set_y(ui_EntryKeyboard, -94);
    lv_obj_set_align(ui_EntryKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_OKTick = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_OKTick, &ui_img_tick_png);
    lv_obj_set_width(ui_OKTick, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OKTick, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OKTick, 0);
    lv_obj_set_y(ui_OKTick, 194);
    lv_obj_set_align(ui_OKTick, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OKTick, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OKTick, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_PreviousButton, ui_event_PreviousButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Footswitch1Label, ui_event_Footswitch1Label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PreviousContainer, ui_event_PreviousContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButton, ui_event_NextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Footswitch2Label, ui_event_Footswitch2Label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextContainer, ui_event_NextContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsImage, ui_event_SettingsImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTStatusDisconn, ui_event_BTStatusDisconn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PresetHeadingLabel, ui_event_PresetHeadingLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PresetDetailsTextArea, ui_event_PresetDetailsTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LeftArrow, ui_event_LeftArrow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RightArrow, ui_event_RightArrow, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_EntryKeyboard, ui_PresetDetailsTextArea);
    lv_obj_add_event_cb(ui_EntryKeyboard, ui_event_EntryKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OKTick, ui_event_OKTick, LV_EVENT_ALL, NULL);

}
