// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsTabview = lv_tabview_create(ui_Settings, LV_DIR_TOP, 60);
    lv_obj_set_width(ui_SettingsTabview, 780);
    lv_obj_set_height(ui_SettingsTabview, 428);
    lv_obj_set_x(ui_SettingsTabview, -1);
    lv_obj_set_y(ui_SettingsTabview, -18);
    lv_obj_set_align(ui_SettingsTabview, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingsTabview,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SettingsTabview, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsTabview, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SettingsTabview, lv_color_hex(0x563F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SettingsTabview, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsTabview, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsTabview, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsTabview, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_SettingsTabview), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0x2A2A2A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0xFDFBFB),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0x3D3D3D),
                              LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0x8D801A),
                                  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_NoiseGateTab = lv_tabview_add_tab(ui_SettingsTabview, "Gate");
    lv_obj_clear_flag(ui_NoiseGateTab, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_NoiseGateEnableGroup = lv_obj_create(ui_NoiseGateTab);
    lv_obj_remove_style_all(ui_NoiseGateEnableGroup);
    lv_obj_set_width(ui_NoiseGateEnableGroup, 309);
    lv_obj_set_height(ui_NoiseGateEnableGroup, 36);
    lv_obj_set_x(ui_NoiseGateEnableGroup, -221);
    lv_obj_set_y(ui_NoiseGateEnableGroup, -146);
    lv_obj_set_align(ui_NoiseGateEnableGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NoiseGateEnableGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateSwitch = lv_switch_create(ui_NoiseGateEnableGroup);
    lv_obj_set_width(ui_NoiseGateSwitch, 50);
    lv_obj_set_height(ui_NoiseGateSwitch, 25);
    lv_obj_set_x(ui_NoiseGateSwitch, 145);
    lv_obj_set_y(ui_NoiseGateSwitch, 0);
    lv_obj_set_align(ui_NoiseGateSwitch, LV_ALIGN_LEFT_MID);


    ui_NoiseGateEnableLabel = lv_label_create(ui_NoiseGateEnableGroup);
    lv_obj_set_width(ui_NoiseGateEnableLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateEnableLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateEnableLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateEnableLabel, "Enable");
    lv_obj_set_style_text_font(ui_NoiseGateEnableLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdGroup = lv_obj_create(ui_NoiseGateTab);
    lv_obj_remove_style_all(ui_NoiseGateThresholdGroup);
    lv_obj_set_width(ui_NoiseGateThresholdGroup, 752);
    lv_obj_set_height(ui_NoiseGateThresholdGroup, 36);
    lv_obj_set_x(ui_NoiseGateThresholdGroup, -3);
    lv_obj_set_y(ui_NoiseGateThresholdGroup, -90);
    lv_obj_set_align(ui_NoiseGateThresholdGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NoiseGateThresholdGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider = lv_slider_create(ui_NoiseGateThresholdGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel = lv_label_create(ui_NoiseGateThresholdGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel, "Threshold");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoiseGateReleaseGroup = lv_obj_create(ui_NoiseGateTab);
    lv_obj_remove_style_all(ui_NoiseGateReleaseGroup);
    lv_obj_set_width(ui_NoiseGateReleaseGroup, 752);
    lv_obj_set_height(ui_NoiseGateReleaseGroup, 36);
    lv_obj_set_x(ui_NoiseGateReleaseGroup, -3);
    lv_obj_set_y(ui_NoiseGateReleaseGroup, -34);
    lv_obj_set_align(ui_NoiseGateReleaseGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NoiseGateReleaseGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateReleaseSlider = lv_slider_create(ui_NoiseGateReleaseGroup);
    lv_slider_set_value(ui_NoiseGateReleaseSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateReleaseSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateReleaseSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateReleaseSlider, 569);
    lv_obj_set_height(ui_NoiseGateReleaseSlider, 10);
    lv_obj_set_x(ui_NoiseGateReleaseSlider, 160);
    lv_obj_set_y(ui_NoiseGateReleaseSlider, 0);
    lv_obj_set_align(ui_NoiseGateReleaseSlider, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateReleaseSlider, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateReleaseSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateReleaseSlider, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateReleaseSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateReleaseSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateReleaseSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateReleaseLabel = lv_label_create(ui_NoiseGateReleaseGroup);
    lv_obj_set_width(ui_NoiseGateReleaseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateReleaseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateReleaseLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateReleaseLabel, "Release");
    lv_obj_set_style_text_font(ui_NoiseGateReleaseLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoiseGateDepthGroup = lv_obj_create(ui_NoiseGateTab);
    lv_obj_remove_style_all(ui_NoiseGateDepthGroup);
    lv_obj_set_width(ui_NoiseGateDepthGroup, 752);
    lv_obj_set_height(ui_NoiseGateDepthGroup, 36);
    lv_obj_set_x(ui_NoiseGateDepthGroup, -3);
    lv_obj_set_y(ui_NoiseGateDepthGroup, 22);
    lv_obj_set_align(ui_NoiseGateDepthGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NoiseGateDepthGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateDepthSlider = lv_slider_create(ui_NoiseGateDepthGroup);
    lv_slider_set_value(ui_NoiseGateDepthSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateDepthSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateDepthSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateDepthSlider, 569);
    lv_obj_set_height(ui_NoiseGateDepthSlider, 10);
    lv_obj_set_x(ui_NoiseGateDepthSlider, 160);
    lv_obj_set_y(ui_NoiseGateDepthSlider, 0);
    lv_obj_set_align(ui_NoiseGateDepthSlider, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateDepthSlider, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateDepthSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateDepthSlider, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateDepthSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateDepthSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateDepthSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateDepthLabel = lv_label_create(ui_NoiseGateDepthGroup);
    lv_obj_set_width(ui_NoiseGateDepthLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateDepthLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateDepthLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateDepthLabel, "Depth");
    lv_obj_set_style_text_font(ui_NoiseGateDepthLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompressorTag = lv_tabview_add_tab(ui_SettingsTabview, "Comp");
    lv_obj_clear_flag(ui_CompressorTag, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_CompressorEnableGroup = lv_obj_create(ui_CompressorTag);
    lv_obj_remove_style_all(ui_CompressorEnableGroup);
    lv_obj_set_width(ui_CompressorEnableGroup, 309);
    lv_obj_set_height(ui_CompressorEnableGroup, 36);
    lv_obj_set_x(ui_CompressorEnableGroup, -221);
    lv_obj_set_y(ui_CompressorEnableGroup, -146);
    lv_obj_set_align(ui_CompressorEnableGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CompressorEnableGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateSwitch2 = lv_switch_create(ui_CompressorEnableGroup);
    lv_obj_set_width(ui_NoiseGateSwitch2, 50);
    lv_obj_set_height(ui_NoiseGateSwitch2, 25);
    lv_obj_set_x(ui_NoiseGateSwitch2, 145);
    lv_obj_set_y(ui_NoiseGateSwitch2, 0);
    lv_obj_set_align(ui_NoiseGateSwitch2, LV_ALIGN_LEFT_MID);


    ui_NoiseGateEnableLabel2 = lv_label_create(ui_CompressorEnableGroup);
    lv_obj_set_width(ui_NoiseGateEnableLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateEnableLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateEnableLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateEnableLabel2, "Enable");
    lv_obj_set_style_text_font(ui_NoiseGateEnableLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompressorPostGroup = lv_obj_create(ui_CompressorTag);
    lv_obj_remove_style_all(ui_CompressorPostGroup);
    lv_obj_set_width(ui_CompressorPostGroup, 309);
    lv_obj_set_height(ui_CompressorPostGroup, 36);
    lv_obj_set_x(ui_CompressorPostGroup, -221);
    lv_obj_set_y(ui_CompressorPostGroup, -90);
    lv_obj_set_align(ui_CompressorPostGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CompressorPostGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateSwitch5 = lv_switch_create(ui_CompressorPostGroup);
    lv_obj_set_width(ui_NoiseGateSwitch5, 50);
    lv_obj_set_height(ui_NoiseGateSwitch5, 25);
    lv_obj_set_x(ui_NoiseGateSwitch5, 145);
    lv_obj_set_y(ui_NoiseGateSwitch5, 0);
    lv_obj_set_align(ui_NoiseGateSwitch5, LV_ALIGN_LEFT_MID);


    ui_NoiseGateEnableLabel5 = lv_label_create(ui_CompressorPostGroup);
    lv_obj_set_width(ui_NoiseGateEnableLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateEnableLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateEnableLabel5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateEnableLabel5, "Post");
    lv_obj_set_style_text_font(ui_NoiseGateEnableLabel5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompressorThresholdGroup = lv_obj_create(ui_CompressorTag);
    lv_obj_remove_style_all(ui_CompressorThresholdGroup);
    lv_obj_set_width(ui_CompressorThresholdGroup, 752);
    lv_obj_set_height(ui_CompressorThresholdGroup, 36);
    lv_obj_set_x(ui_CompressorThresholdGroup, -3);
    lv_obj_set_y(ui_CompressorThresholdGroup, -34);
    lv_obj_set_align(ui_CompressorThresholdGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CompressorThresholdGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider2 = lv_slider_create(ui_CompressorThresholdGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider2, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider2, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider2, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider2, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider2, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider2, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider2, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel2 = lv_label_create(ui_CompressorThresholdGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel2, "Threshold");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompressorAttackGroup = lv_obj_create(ui_CompressorTag);
    lv_obj_remove_style_all(ui_CompressorAttackGroup);
    lv_obj_set_width(ui_CompressorAttackGroup, 752);
    lv_obj_set_height(ui_CompressorAttackGroup, 36);
    lv_obj_set_x(ui_CompressorAttackGroup, -1);
    lv_obj_set_y(ui_CompressorAttackGroup, 22);
    lv_obj_set_align(ui_CompressorAttackGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CompressorAttackGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider1 = lv_slider_create(ui_CompressorAttackGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider1, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider1, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider1, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider1, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider1, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider1, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel1 = lv_label_create(ui_CompressorAttackGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel1, "Attack");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompressorMakeupGroup = lv_obj_create(ui_CompressorTag);
    lv_obj_remove_style_all(ui_CompressorMakeupGroup);
    lv_obj_set_width(ui_CompressorMakeupGroup, 752);
    lv_obj_set_height(ui_CompressorMakeupGroup, 36);
    lv_obj_set_x(ui_CompressorMakeupGroup, -1);
    lv_obj_set_y(ui_CompressorMakeupGroup, 78);
    lv_obj_set_align(ui_CompressorMakeupGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CompressorMakeupGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider6 = lv_slider_create(ui_CompressorMakeupGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider6, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider6, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider6, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider6, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider6, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider6, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider6, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider6, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider6, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider6, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel6 = lv_label_create(ui_CompressorMakeupGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel6, "Makeup");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EQTab = lv_tabview_add_tab(ui_SettingsTabview, "EQ");
    lv_obj_clear_flag(ui_EQTab, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_EQPrePostGroup = lv_obj_create(ui_EQTab);
    lv_obj_remove_style_all(ui_EQPrePostGroup);
    lv_obj_set_width(ui_EQPrePostGroup, 309);
    lv_obj_set_height(ui_EQPrePostGroup, 36);
    lv_obj_set_x(ui_EQPrePostGroup, -221);
    lv_obj_set_y(ui_EQPrePostGroup, -146);
    lv_obj_set_align(ui_EQPrePostGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EQPrePostGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateSwitch4 = lv_switch_create(ui_EQPrePostGroup);
    lv_obj_set_width(ui_NoiseGateSwitch4, 50);
    lv_obj_set_height(ui_NoiseGateSwitch4, 25);
    lv_obj_set_x(ui_NoiseGateSwitch4, 145);
    lv_obj_set_y(ui_NoiseGateSwitch4, 0);
    lv_obj_set_align(ui_NoiseGateSwitch4, LV_ALIGN_LEFT_MID);


    ui_NoiseGateEnableLabel4 = lv_label_create(ui_EQPrePostGroup);
    lv_obj_set_width(ui_NoiseGateEnableLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateEnableLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateEnableLabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateEnableLabel4, "Post");
    lv_obj_set_style_text_font(ui_NoiseGateEnableLabel4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EQBassFreqGroup = lv_obj_create(ui_EQTab);
    lv_obj_remove_style_all(ui_EQBassFreqGroup);
    lv_obj_set_width(ui_EQBassFreqGroup, 752);
    lv_obj_set_height(ui_EQBassFreqGroup, 36);
    lv_obj_set_x(ui_EQBassFreqGroup, -1);
    lv_obj_set_y(ui_EQBassFreqGroup, -90);
    lv_obj_set_align(ui_EQBassFreqGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EQBassFreqGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider4 = lv_slider_create(ui_EQBassFreqGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider4, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider4, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider4, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider4, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider4, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider4, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider4, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider4, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel4 = lv_label_create(ui_EQBassFreqGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel4, "Bass Freq");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EQMidFreqGroup = lv_obj_create(ui_EQTab);
    lv_obj_remove_style_all(ui_EQMidFreqGroup);
    lv_obj_set_width(ui_EQMidFreqGroup, 752);
    lv_obj_set_height(ui_EQMidFreqGroup, 36);
    lv_obj_set_x(ui_EQMidFreqGroup, -1);
    lv_obj_set_y(ui_EQMidFreqGroup, -34);
    lv_obj_set_align(ui_EQMidFreqGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EQMidFreqGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider3 = lv_slider_create(ui_EQMidFreqGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider3, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider3, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider3, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider3, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider3, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider3, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider3, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider3, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel3 = lv_label_create(ui_EQMidFreqGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel3, "Mid Freq");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EQTrebleFreqGroup = lv_obj_create(ui_EQTab);
    lv_obj_remove_style_all(ui_EQTrebleFreqGroup);
    lv_obj_set_width(ui_EQTrebleFreqGroup, 752);
    lv_obj_set_height(ui_EQTrebleFreqGroup, 36);
    lv_obj_set_x(ui_EQTrebleFreqGroup, -1);
    lv_obj_set_y(ui_EQTrebleFreqGroup, 22);
    lv_obj_set_align(ui_EQTrebleFreqGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EQTrebleFreqGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider7 = lv_slider_create(ui_EQTrebleFreqGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider7, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider7, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider7, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider7, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider7, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider7, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider7, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider7, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider7, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider7, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel7 = lv_label_create(ui_EQTrebleFreqGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel7, "Treble Freq");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReverbPage = lv_tabview_add_tab(ui_SettingsTabview, "Reverb");
    lv_obj_clear_flag(ui_ReverbPage, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ReverbEnableGroup = lv_obj_create(ui_ReverbPage);
    lv_obj_remove_style_all(ui_ReverbEnableGroup);
    lv_obj_set_width(ui_ReverbEnableGroup, 309);
    lv_obj_set_height(ui_ReverbEnableGroup, 36);
    lv_obj_set_x(ui_ReverbEnableGroup, -221);
    lv_obj_set_y(ui_ReverbEnableGroup, -146);
    lv_obj_set_align(ui_ReverbEnableGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ReverbEnableGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateSwitch3 = lv_switch_create(ui_ReverbEnableGroup);
    lv_obj_set_width(ui_NoiseGateSwitch3, 50);
    lv_obj_set_height(ui_NoiseGateSwitch3, 25);
    lv_obj_set_x(ui_NoiseGateSwitch3, 145);
    lv_obj_set_y(ui_NoiseGateSwitch3, 0);
    lv_obj_set_align(ui_NoiseGateSwitch3, LV_ALIGN_LEFT_MID);


    ui_NoiseGateEnableLabel3 = lv_label_create(ui_ReverbEnableGroup);
    lv_obj_set_width(ui_NoiseGateEnableLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateEnableLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateEnableLabel3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateEnableLabel3, "Enable");
    lv_obj_set_style_text_font(ui_NoiseGateEnableLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReverbMixGroup = lv_obj_create(ui_ReverbPage);
    lv_obj_remove_style_all(ui_ReverbMixGroup);
    lv_obj_set_width(ui_ReverbMixGroup, 752);
    lv_obj_set_height(ui_ReverbMixGroup, 36);
    lv_obj_set_x(ui_ReverbMixGroup, -1);
    lv_obj_set_y(ui_ReverbMixGroup, -90);
    lv_obj_set_align(ui_ReverbMixGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ReverbMixGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider9 = lv_slider_create(ui_ReverbMixGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider9, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider9) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider9, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider9, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider9, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider9, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider9, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider9, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider9, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider9, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider9, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider9, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel9 = lv_label_create(ui_ReverbMixGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel9, "Mix");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReverbMixGroup1 = lv_obj_create(ui_ReverbPage);
    lv_obj_remove_style_all(ui_ReverbMixGroup1);
    lv_obj_set_width(ui_ReverbMixGroup1, 752);
    lv_obj_set_height(ui_ReverbMixGroup1, 36);
    lv_obj_set_x(ui_ReverbMixGroup1, -1);
    lv_obj_set_y(ui_ReverbMixGroup1, -34);
    lv_obj_set_align(ui_ReverbMixGroup1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ReverbMixGroup1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider8 = lv_slider_create(ui_ReverbMixGroup1);
    lv_slider_set_value(ui_NoiseGateThresholdSlider8, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider8) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider8, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider8, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider8, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider8, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider8, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider8, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider8, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider8, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider8, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel8 = lv_label_create(ui_ReverbMixGroup1);
    lv_obj_set_width(ui_NoiseGateThresholdLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel8, "Time");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReverbPredelayGroup = lv_obj_create(ui_ReverbPage);
    lv_obj_remove_style_all(ui_ReverbPredelayGroup);
    lv_obj_set_width(ui_ReverbPredelayGroup, 752);
    lv_obj_set_height(ui_ReverbPredelayGroup, 36);
    lv_obj_set_x(ui_ReverbPredelayGroup, -1);
    lv_obj_set_y(ui_ReverbPredelayGroup, 22);
    lv_obj_set_align(ui_ReverbPredelayGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ReverbPredelayGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider11 = lv_slider_create(ui_ReverbPredelayGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider11, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider11) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider11, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider11, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider11, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider11, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider11, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider11, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider11, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider11, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider11, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider11, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider11, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel11 = lv_label_create(ui_ReverbPredelayGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel11, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel11, "Pre-Delay");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel11, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReverbColorGroup = lv_obj_create(ui_ReverbPage);
    lv_obj_remove_style_all(ui_ReverbColorGroup);
    lv_obj_set_width(ui_ReverbColorGroup, 752);
    lv_obj_set_height(ui_ReverbColorGroup, 36);
    lv_obj_set_x(ui_ReverbColorGroup, -1);
    lv_obj_set_y(ui_ReverbColorGroup, 78);
    lv_obj_set_align(ui_ReverbColorGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ReverbColorGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider12 = lv_slider_create(ui_ReverbColorGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider12, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider12) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider12, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider12, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider12, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider12, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider12, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider12, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider12, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider12, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider12, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider12, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider12, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel12 = lv_label_create(ui_ReverbColorGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel12, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel12, "Color");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel12, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GlobalTab = lv_tabview_add_tab(ui_SettingsTabview, "Global");
    lv_obj_clear_flag(ui_GlobalTab, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_GlobalInputTrimGroup = lv_obj_create(ui_GlobalTab);
    lv_obj_remove_style_all(ui_GlobalInputTrimGroup);
    lv_obj_set_width(ui_GlobalInputTrimGroup, 752);
    lv_obj_set_height(ui_GlobalInputTrimGroup, 36);
    lv_obj_set_x(ui_GlobalInputTrimGroup, -1);
    lv_obj_set_y(ui_GlobalInputTrimGroup, -146);
    lv_obj_set_align(ui_GlobalInputTrimGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GlobalInputTrimGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider5 = lv_slider_create(ui_GlobalInputTrimGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider5, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider5, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider5, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider5, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider5, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider5, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider5, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider5, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel5 = lv_label_create(ui_GlobalInputTrimGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel5, "Input Trim");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GlobalVolumeGroup = lv_obj_create(ui_GlobalTab);
    lv_obj_remove_style_all(ui_GlobalVolumeGroup);
    lv_obj_set_width(ui_GlobalVolumeGroup, 752);
    lv_obj_set_height(ui_GlobalVolumeGroup, 36);
    lv_obj_set_x(ui_GlobalVolumeGroup, -1);
    lv_obj_set_y(ui_GlobalVolumeGroup, -90);
    lv_obj_set_align(ui_GlobalVolumeGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GlobalVolumeGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateThresholdSlider10 = lv_slider_create(ui_GlobalVolumeGroup);
    lv_slider_set_value(ui_NoiseGateThresholdSlider10, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_NoiseGateThresholdSlider10) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_NoiseGateThresholdSlider10, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseGateThresholdSlider10, 569);
    lv_obj_set_height(ui_NoiseGateThresholdSlider10, 10);
    lv_obj_set_x(ui_NoiseGateThresholdSlider10, 160);
    lv_obj_set_y(ui_NoiseGateThresholdSlider10, 0);
    lv_obj_set_align(ui_NoiseGateThresholdSlider10, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider10, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider10, lv_color_hex(0xC7C6C5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider10, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_NoiseGateThresholdSlider10, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseGateThresholdSlider10, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_NoiseGateThresholdLabel10 = lv_label_create(ui_GlobalVolumeGroup);
    lv_obj_set_width(ui_NoiseGateThresholdLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateThresholdLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateThresholdLabel10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateThresholdLabel10, "Global Vol");
    lv_obj_set_style_text_font(ui_NoiseGateThresholdLabel10, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GlobalCabinetGroup = lv_obj_create(ui_GlobalTab);
    lv_obj_remove_style_all(ui_GlobalCabinetGroup);
    lv_obj_set_width(ui_GlobalCabinetGroup, 309);
    lv_obj_set_height(ui_GlobalCabinetGroup, 36);
    lv_obj_set_x(ui_GlobalCabinetGroup, -221);
    lv_obj_set_y(ui_GlobalCabinetGroup, -34);
    lv_obj_set_align(ui_GlobalCabinetGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GlobalCabinetGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NoiseGateSwitch6 = lv_switch_create(ui_GlobalCabinetGroup);
    lv_obj_set_width(ui_NoiseGateSwitch6, 50);
    lv_obj_set_height(ui_NoiseGateSwitch6, 25);
    lv_obj_set_x(ui_NoiseGateSwitch6, 145);
    lv_obj_set_y(ui_NoiseGateSwitch6, 0);
    lv_obj_set_align(ui_NoiseGateSwitch6, LV_ALIGN_LEFT_MID);


    ui_NoiseGateEnableLabel6 = lv_label_create(ui_GlobalCabinetGroup);
    lv_obj_set_width(ui_NoiseGateEnableLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NoiseGateEnableLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NoiseGateEnableLabel6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_NoiseGateEnableLabel6, "Cabinet");
    lv_obj_set_style_text_font(ui_NoiseGateEnableLabel6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CloseImage = lv_img_create(ui_Settings);
    lv_img_set_src(ui_CloseImage, &ui_img_tick_png);
    lv_obj_set_width(ui_CloseImage, 86);
    lv_obj_set_height(ui_CloseImage, 62);
    lv_obj_set_x(ui_CloseImage, 350);
    lv_obj_set_y(ui_CloseImage, 212);
    lv_obj_set_align(ui_CloseImage, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_CloseImage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CloseImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CloseImage, 160);

    lv_obj_add_event_cb(ui_CloseImage, ui_event_CloseImage, LV_EVENT_ALL, NULL);

}
