// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BottomPanel, 800);
    lv_obj_set_height(ui_BottomPanel, 71);
    lv_obj_set_x(ui_BottomPanel, 0);
    lv_obj_set_y(ui_BottomPanel, 203);
    lv_obj_set_align(ui_BottomPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BottomPanel, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BottomPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BottomPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PreviousContainer = lv_obj_create(ui_BottomPanel);
    lv_obj_remove_style_all(ui_PreviousContainer);
    lv_obj_set_width(ui_PreviousContainer, 221);
    lv_obj_set_height(ui_PreviousContainer, 58);
    lv_obj_set_x(ui_PreviousContainer, -200);
    lv_obj_set_y(ui_PreviousContainer, 0);
    lv_obj_set_align(ui_PreviousContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PreviousContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PreviousButton = lv_imgbtn_create(ui_PreviousContainer);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_previous_png, NULL);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_previous_down_png, NULL);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_PreviousButton, 45);
    lv_obj_set_width(ui_PreviousButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_PreviousButton, 69);
    lv_obj_set_y(ui_PreviousButton, 0);
    lv_obj_set_align(ui_PreviousButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PreviousButton, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Footswitch1Label = lv_label_create(ui_PreviousContainer);
    lv_obj_set_width(ui_Footswitch1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Footswitch1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Footswitch1Label, -32);
    lv_obj_set_y(ui_Footswitch1Label, -4);
    lv_obj_set_align(ui_Footswitch1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Footswitch1Label, "Previous");
    lv_obj_set_style_text_color(ui_Footswitch1Label, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Footswitch1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Footswitch1Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextContainer = lv_obj_create(ui_BottomPanel);
    lv_obj_remove_style_all(ui_NextContainer);
    lv_obj_set_width(ui_NextContainer, 221);
    lv_obj_set_height(ui_NextContainer, 58);
    lv_obj_set_x(ui_NextContainer, 200);
    lv_obj_set_y(ui_NextContainer, 0);
    lv_obj_set_align(ui_NextContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NextContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextButton = lv_imgbtn_create(ui_NextContainer);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_next_png, NULL);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_next_down_png, NULL);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
    lv_obj_set_height(ui_NextButton, 45);
    lv_obj_set_width(ui_NextButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_NextButton, 44);
    lv_obj_set_y(ui_NextButton, 0);
    lv_obj_set_align(ui_NextButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NextButton, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Footswitch2Label = lv_label_create(ui_NextContainer);
    lv_obj_set_width(ui_Footswitch2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Footswitch2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Footswitch2Label, -30);
    lv_obj_set_y(ui_Footswitch2Label, -2);
    lv_obj_set_align(ui_Footswitch2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Footswitch2Label, "Next");
    lv_obj_set_style_text_color(ui_Footswitch2Label, lv_color_hex(0xC0C0C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Footswitch2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Footswitch2Label, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopPanel, 800);
    lv_obj_set_height(ui_TopPanel, 51);
    lv_obj_set_x(ui_TopPanel, 1);
    lv_obj_set_y(ui_TopPanel, -215);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IKLogo = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_IKLogo, &ui_img_smythbuilt_png);
    lv_obj_set_width(ui_IKLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IKLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IKLogo, -331);
    lv_obj_set_y(ui_IKLogo, 0);
    lv_obj_set_align(ui_IKLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IKLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IKLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTStatusConn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_BTStatusConn, &ui_img_bt_conn_png);
    lv_obj_set_width(ui_BTStatusConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatusConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatusConn, 301);
    lv_obj_set_y(ui_BTStatusConn, -2);
    lv_obj_set_align(ui_BTStatusConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTStatusConn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTStatusConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTStatusDisconn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_BTStatusDisconn, &ui_img_bt_disconn_png);
    lv_obj_set_width(ui_BTStatusDisconn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatusDisconn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatusDisconn, 301);
    lv_obj_set_y(ui_BTStatusDisconn, -2);
    lv_obj_set_align(ui_BTStatusDisconn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTStatusDisconn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTStatusDisconn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_USBStatusOK = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_USBStatusOK, &ui_img_usb_ok_png);
    lv_obj_set_width(ui_USBStatusOK, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_USBStatusOK, LV_SIZE_CONTENT);    /// 77
    lv_obj_set_x(ui_USBStatusOK, 356);
    lv_obj_set_y(ui_USBStatusOK, -1);
    lv_obj_set_align(ui_USBStatusOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_USBStatusOK, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_USBStatusOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_USBStatusFail = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_USBStatusFail, &ui_img_usb_fail_png);
    lv_obj_set_width(ui_USBStatusFail, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_USBStatusFail, LV_SIZE_CONTENT);    /// 77
    lv_obj_set_x(ui_USBStatusFail, 356);
    lv_obj_set_y(ui_USBStatusFail, -1);
    lv_obj_set_align(ui_USBStatusFail, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_USBStatusFail, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_USBStatusFail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProjectHeadingLabel = lv_label_create(ui_TopPanel);
    lv_obj_set_width(ui_ProjectHeadingLabel, 508);
    lv_obj_set_height(ui_ProjectHeadingLabel, 38);
    lv_obj_set_align(ui_ProjectHeadingLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ProjectHeadingLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_ProjectHeadingLabel, "TONEX Controller");
    lv_obj_set_style_text_color(ui_ProjectHeadingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProjectHeadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProjectHeadingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProjectHeadingLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AmpSkins = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_AmpSkins);
    lv_obj_set_width(ui_AmpSkins, 460);
    lv_obj_set_height(ui_AmpSkins, 143);
    lv_obj_set_x(ui_AmpSkins, 0);
    lv_obj_set_y(ui_AmpSkins, -20);
    lv_obj_set_align(ui_AmpSkins, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AmpSkins, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ampjcm800 = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_Ampjcm800, &ui_img_skin_jcm800_png);
    lv_obj_set_width(ui_Ampjcm800, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ampjcm800, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ampjcm800, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ampjcm800, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ampjcm800, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Amptwinreverb = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_Amptwinreverb, &ui_img_skin_twinreverb_png);
    lv_obj_set_width(ui_Amptwinreverb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amptwinreverb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Amptwinreverb, 0);
    lv_obj_set_y(ui_Amptwinreverb, -12);
    lv_obj_set_align(ui_Amptwinreverb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Amptwinreverb, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Amptwinreverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Amp2001rb = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_Amp2001rb, &ui_img_skin_2001rb_png);
    lv_obj_set_width(ui_Amp2001rb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amp2001rb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Amp2001rb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Amp2001rb, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Amp2001rb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Amp5150 = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_Amp5150, &ui_img_skin_5150_png);
    lv_obj_set_width(ui_Amp5150, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amp5150, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Amp5150, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Amp5150, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Amp5150, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpAcoustic360 = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpAcoustic360, &ui_img_skin_acoustic360_png);
    lv_obj_set_width(ui_AmpAcoustic360, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpAcoustic360, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpAcoustic360, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpAcoustic360, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpAcoustic360, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ampb18n = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_Ampb18n, &ui_img_skin_b18n_png);
    lv_obj_set_width(ui_Ampb18n, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ampb18n, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ampb18n, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ampb18n, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ampb18n, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ampb15n = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_Ampb15n, &ui_img_skin_b51n_png);
    lv_obj_set_width(ui_Ampb15n, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ampb15n, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ampb15n, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Ampb15n, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Ampb15n, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpbBluesdeluxe = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpbBluesdeluxe, &ui_img_skin_bluesdeluxe_png);
    lv_obj_set_width(ui_AmpbBluesdeluxe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpbBluesdeluxe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpbBluesdeluxe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpbBluesdeluxe, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpbBluesdeluxe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpbCustomDeluxe = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpbCustomDeluxe, &ui_img_skin_customdeluxe_png);
    lv_obj_set_width(ui_AmpbCustomDeluxe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpbCustomDeluxe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpbCustomDeluxe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpbCustomDeluxe, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpbCustomDeluxe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpbDeville = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpbDeville, &ui_img_skin_deville_png);
    lv_obj_set_width(ui_AmpbDeville, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpbDeville, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpbDeville, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpbDeville, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpbDeville, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpbDualrectifier = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpbDualrectifier, &ui_img_skin_dualrectifier_png);
    lv_obj_set_width(ui_AmpbDualrectifier, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpbDualrectifier, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpbDualrectifier, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpbDualrectifier, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpbDualrectifier, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpbGoldfinger = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpbGoldfinger, &ui_img_skin_goldfinger_png);
    lv_obj_set_width(ui_AmpbGoldfinger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpbGoldfinger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpbGoldfinger, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpbGoldfinger, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpbGoldfinger, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpbInvader = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpbInvader, &ui_img_skin_invader_png);
    lv_obj_set_width(ui_AmpbInvader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpbInvader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpbInvader, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpbInvader, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpbInvader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpJazzchorus = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpJazzchorus, &ui_img_skin_jazzchorus_png);
    lv_obj_set_width(ui_AmpJazzchorus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpJazzchorus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpJazzchorus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpJazzchorus, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpJazzchorus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpOr50 = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpOr50, &ui_img_skin_or50_png);
    lv_obj_set_width(ui_AmpOr50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpOr50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpOr50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpOr50, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpOr50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpPowerball = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpPowerball, &ui_img_skin_powerball_png);
    lv_obj_set_width(ui_AmpPowerball, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpPowerball, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpPowerball, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpPowerball, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpPowerball, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpPrinceton = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpPrinceton, &ui_img_skin_princeton_png);
    lv_obj_set_width(ui_AmpPrinceton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpPrinceton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpPrinceton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpPrinceton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpPrinceton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpRockerverb = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpRockerverb, &ui_img_skin_rockerverb_png);
    lv_obj_set_width(ui_AmpRockerverb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpRockerverb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpRockerverb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpRockerverb, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpRockerverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpSvtcl = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpSvtcl, &ui_img_skin_svtcl_png);
    lv_obj_set_width(ui_AmpSvtcl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpSvtcl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpSvtcl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpSvtcl, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpSvtcl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpMaverick = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpMaverick, &ui_img_skin_maverick_png);
    lv_obj_set_width(ui_AmpMaverick, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpMaverick, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpMaverick, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpMaverick, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpMaverick, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpMk3 = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpMk3, &ui_img_skin_mk3_png);
    lv_obj_set_width(ui_AmpMk3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpMk3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpMk3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpMk3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpMk3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpSuperbass = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpSuperbass, &ui_img_skin_superbass_png);
    lv_obj_set_width(ui_AmpSuperbass, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpSuperbass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpSuperbass, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpSuperbass, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpSuperbass, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpTrinity = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpTrinity, &ui_img_skin_trinity_png);
    lv_obj_set_width(ui_AmpTrinity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpTrinity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpTrinity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpTrinity, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpTrinity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpDumble = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpDumble, &ui_img_skin_dumble_png);
    lv_obj_set_width(ui_AmpDumble, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpDumble, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpDumble, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpDumble, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpDumble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpJetcity = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpJetcity, &ui_img_skin_jetcity_png);
    lv_obj_set_width(ui_AmpJetcity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpJetcity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpJetcity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpJetcity, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpJetcity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpAC30 = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpAC30, &ui_img_skin_ac30_png);
    lv_obj_set_width(ui_AmpAC30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpAC30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpAC30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpAC30, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpAC30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpEvh5150 = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpEvh5150, &ui_img_skin_evh5150_png);
    lv_obj_set_width(ui_AmpEvh5150, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpEvh5150, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpEvh5150, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpEvh5150, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpEvh5150, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpTinyterror = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpTinyterror, &ui_img_skin_tinyterror_png);
    lv_obj_set_width(ui_AmpTinyterror, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpTinyterror, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpTinyterror, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpTinyterror, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpTinyterror, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Amp2020 = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_Amp2020, &ui_img_skin_2020_png);
    lv_obj_set_width(ui_Amp2020, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Amp2020, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Amp2020, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Amp2020, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Amp2020, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpPinktaco = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpPinktaco, &ui_img_skin_pinktaco_png);
    lv_obj_set_width(ui_AmpPinktaco, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpPinktaco, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpPinktaco, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpPinktaco, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpPinktaco, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpSupro50 = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpSupro50, &ui_img_skin_supro50_png);
    lv_obj_set_width(ui_AmpSupro50, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpSupro50, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpSupro50, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpSupro50, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpSupro50, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmpDiezel = lv_img_create(ui_AmpSkins);
    lv_img_set_src(ui_AmpDiezel, &ui_img_skin_diezel_png);
    lv_obj_set_width(ui_AmpDiezel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpDiezel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AmpDiezel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AmpDiezel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AmpDiezel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PresetHeadingLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PresetHeadingLabel, 789);
    lv_obj_set_height(ui_PresetHeadingLabel, 60);
    lv_obj_set_x(ui_PresetHeadingLabel, 0);
    lv_obj_set_y(ui_PresetHeadingLabel, -136);
    lv_obj_set_align(ui_PresetHeadingLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PresetHeadingLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_PresetHeadingLabel, "Preset Name");
    lv_obj_add_flag(ui_PresetHeadingLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_PresetHeadingLabel, lv_color_hex(0xD1A60C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetHeadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetHeadingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetHeadingLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetDetailsTextArea = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_PresetDetailsTextArea, 773);
    lv_obj_set_height(ui_PresetDetailsTextArea, 99);
    lv_obj_set_x(ui_PresetDetailsTextArea, 0);
    lv_obj_set_y(ui_PresetDetailsTextArea, 110);
    lv_obj_set_align(ui_PresetDetailsTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PresetDetailsTextArea, 128);
    lv_textarea_set_placeholder_text(ui_PresetDetailsTextArea, "Preset Description...");
    lv_obj_add_state(ui_PresetDetailsTextArea, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_font(ui_PresetDetailsTextArea, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetDetailsTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetDetailsTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetDetailsTextArea, lv_color_hex(0x563F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetDetailsTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_LeftArrow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_LeftArrow, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_LeftArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LeftArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LeftArrow, -270);
    lv_obj_set_y(ui_LeftArrow, -15);
    lv_obj_set_align(ui_LeftArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LeftArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RightArrow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_RightArrow, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_RightArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RightArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RightArrow, 270);
    lv_obj_set_y(ui_RightArrow, -15);
    lv_obj_set_align(ui_RightArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RightArrow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RightArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EntryKeyboard = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_EntryKeyboard, 799);
    lv_obj_set_height(ui_EntryKeyboard, 287);
    lv_obj_set_x(ui_EntryKeyboard, 0);
    lv_obj_set_y(ui_EntryKeyboard, -94);
    lv_obj_set_align(ui_EntryKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_OKTick = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_OKTick, &ui_img_tick_png);
    lv_obj_set_width(ui_OKTick, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OKTick, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OKTick, 0);
    lv_obj_set_y(ui_OKTick, 194);
    lv_obj_set_align(ui_OKTick, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OKTick, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OKTick, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_PreviousButton, ui_event_PreviousButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Footswitch1Label, ui_event_Footswitch1Label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PreviousContainer, ui_event_PreviousContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButton, ui_event_NextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Footswitch2Label, ui_event_Footswitch2Label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextContainer, ui_event_NextContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTStatusDisconn, ui_event_BTStatusDisconn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PresetHeadingLabel, ui_event_PresetHeadingLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PresetDetailsTextArea, ui_event_PresetDetailsTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LeftArrow, ui_event_LeftArrow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RightArrow, ui_event_RightArrow, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_EntryKeyboard, ui_PresetDetailsTextArea);
    lv_obj_add_event_cb(ui_EntryKeyboard, ui_event_EntryKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OKTick, ui_event_OKTick, LV_EVENT_ALL, NULL);

}
